set(TARGET_NAME "MyApp")

add_executable(${TARGET_NAME} Package.cpp)
install(TARGETS ${TARGET_NAME} RUNTIME DESTINATION bin)

set(CPACK_PACKAGE_NAME "HelloWrold")
set(CPACK_PACKAGE_VENDOR "MyCompany")
set(CPACK_PACKAGE_DESCTIPTION_SUMMARY "A simple Hello World Application")
set(CPACK_PACKAGE_VERSION "1.0.0")

set(CPACK_GENERATOR "DEB")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Nikita")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
set(CPACK_DEBIAN_PACKAGE_SECTION "utils")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")

include(CPack)