name: CI Pipeline

run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Install Dependencies
           run: |
            sudo apt update
            sudo apt install -y cmake g++

         - name: Configure
           run: cmake -Bbuild -S Servers/Cpp/ -DCMAKE_BUILD_TYPE=Release

         - name: Build
           run: cmake --build build --config Release